const newProducts = [
    { id: "white-onion-powder", name: "White Onion Powder", category: "Dehydrated Vegetables", description: "Premium dehydrated white onion powder. Sharp, sweet flavor, ideal for soups, sauces, and seasoning blends." },
    { id: "white-onion-flakes", name: "White Onion Flakes", category: "Dehydrated Vegetables", description: "Crispy dehydrated white onion flakes. Maintained flavor and texture, perfect for bulk food processing and industrial kitchens." },
    { id: "red-onion-flakes", name: "Red Onion Flakes", category: "Dehydrated Vegetables", description: "Premium dehydrated red onion flakes. Strong aroma and vibrant flavor for culinary applications." },
    { id: "red-onion-powder", name: "Red Onion Powder", category: "Dehydrated Vegetables", description: "Fine red onion powder, highly concentrated flavor. Essential for spice mixes and institutional catering." },
    { id: "ginger-powder", name: "Ginger Powder", category: "Ground Spices", description: "Sun-dried and finely ground ginger powder. High gingerol content, pungent and aromatic." },
    { id: "ginger-flakes", name: "Ginger Flakes", category: "Dehydrated Vegetables", description: "Dehydrated ginger flakes. Ideal for tea blends, confectionery, and medicinal extractions." },
    { id: "garlic-powder", name: "Garlic Powder", category: "Ground Spices", description: "Premium quality garlic powder. Intense flavor, free-flowing, and ideal for spice rubs and seasonings." },
    { id: "garlic-flakes", name: "Garlic Flakes", category: "Dehydrated Vegetables", description: "Sliced and dehydrated garlic flakes. Retains the natural pungency and health benefits of fresh garlic." },
    { id: "amchur-powder", name: "Amchur Powder", category: "Ground Spices", description: "Dry Mango Powder made from raw green mangoes. Key tangy ingredient for Indian street food and curries." },
    { id: "pumpkin-powder", name: "Pumpkin Powder", category: "Dehydrated Vegetables", description: "Nutrient-rich dehydrated pumpkin powder. Natural sweetness and color for bakery and baby food." },
    { id: "pumpkin-flakes", name: "Pumpkin Flakes", category: "Dehydrated Vegetables", description: "Dehydrated pumpkin flakes. Versatile ingredient for soups, stews, and healthy snack bars." },
    { id: "cabbage-powder", name: "Cabbage Powder", category: "Dehydrated Vegetables", description: "Pure dehydrated cabbage powder. Rich in vitamins, ideal for instant soup mixes and nutraceuticals." },
    { id: "cabbage-flakes", name: "Cabbage Flakes", category: "Dehydrated Vegetables", description: "Dried cabbage flakes. Consistent quality and texture for industrial food production." },
    { id: "spinach-powder", name: "Spinach Powder", category: "Dehydrated Vegetables", description: "Bright green dehydrated spinach powder. Superfood ingredient for pasta, smoothies, and natural coloring." },
    { id: "curry-powder", name: "Curry Powder", category: "Blended Spices", description: "Traditional Madras-style curry powder. Perfectly balanced blend for authentic global flavors." },
    { id: "sprouted-chana", name: "Sprouted Chana", category: "Sprouted & Grains", description: "Nutrient-dense sprouted Bengal Gram. High protein, sun-dried for extended shelf life." },
    { id: "bitter-gourd-powder", name: "Bitter Gourd Powder", category: "Wellness & Herbal Powders", description: "Pure Karela powder. Known for managing blood sugar levels and digestive health." },
    { id: "beetroot-powder", name: "Beetroot Powder", category: "Wellness & Herbal Powders", description: "Vibrant red beetroot powder. Natural nitrate source, perfect for sports nutrition and coloring." },
    { id: "moringa-powder", name: "Moringa Powder", category: "Wellness & Herbal Powders", description: "Organic Moringa Oleifera leaf powder. World-renowned superfood with exceptional nutritional profile." },
    { id: "sprouted-matki", name: "Sprouted Matki", category: "Sprouted & Grains", description: "Dehydrated sprouted Moth beans. highly digestible, rich in calcium and iron." },
    { id: "carrot-powder", name: "Carrot Powder", category: "Dehydrated Vegetables", description: "Sweet and nutritious carrot powder. High in Beta-Carotene, ideal for beverages and snacks." },
    { id: "carrot-flakes", name: "Carrot Flakes", category: "Dehydrated Vegetables", description: "Crisp dehydrated carrot flakes. Retains natural color and nutrients for convenience foods." },
    { id: "mint-powder", name: "Mint Powder", category: "Ground Spices", description: "Fragrant dried Pudina powder. Refreshing flavor for beverages, chutneys, and dips." },
    { id: "tamarind-powder", name: "Tamarind Powder", category: "Ground Spices", description: "Tangy tamarind fruit powder. Easy-to-use concentrate for sauces, candies, and soups." },
    { id: "potato-powder", name: "Potato Powder", category: "Dehydrated Vegetables", description: "Versatile potato flour/powder. Excellent thickener for soups and binder for snacks." },
    { id: "potato-flakes", name: "Potato Flakes", category: "Dehydrated Vegetables", description: "Instant potato flakes. Ideal for mashed potatoes, snacks, and industrial baking." },
    { id: "banana-powder", name: "Banana Powder", category: "Specialty Powders", description: "Natural raw banana powder. High resistant starch, ideal for gluten-free baking and baby food." },
    { id: "sprouted-ragi", name: "Sprouted Ragi", category: "Sprouted & Grains", description: "Sprouted and malted Finger Millet powder. Traditional high-calcium weaning food for babies." },
    { id: "french-beans-flakes", name: "French Beans Flakes", category: "Dehydrated Vegetables", description: "Dehydrated green bean flakes. Maintains color and crunch for ready-to-eat meals." },
    { id: "kasuri-methi", name: "Kasuri Methi", category: "Whole Spices", description: "Premium sun-dried Fenugreek leaves. Intense aroma, essential finishing herb for Indian gravies." },
    { id: "amla-powder", name: "Amla Powder", category: "Wellness & Herbal Powders", description: "Indian Gooseberry powder. High Vitamin C, used for immunity and hair care." },
    { id: "shikai-powder", name: "Shikakai Powder", category: "Wellness & Herbal Powders", description: "Natural cleanser for hair. Traditional Ayurvedic powder for healthy scalp." },
    { id: "aloevera-powder", name: "Aloe Vera Powder", category: "Wellness & Herbal Powders", description: "Pure dehydrated Aloe Vera gel powder. Soothing properties for skin and digestion." },
    { id: "hina-powder", name: "Heena Powder", category: "Wellness & Herbal Powders", description: "Natural Lawsonia Inermis powder. Premium grade for hair coloring and art." },
    { id: "tulsi-powder", name: "Tulsi Powder", category: "Wellness & Herbal Powders", description: "Holy Basil leaf powder. Revered for its adaptogenic and respiratory benefits." },
    { id: "ashwagandha-powder", name: "Ashwagandha Powder", category: "Wellness & Herbal Powders", description: "Premium Withania Somnifera root powder. Renowned adaptogen for stress relief and vitality." },
    { id: "dalchini-powder", name: "Dalchini Powder", category: "Ground Spices", description: "Fine Cinnamon powder. Sweet, woody flavor for bakery and beverages." },
    { id: "beetroot-flakes", name: "Beetroot Flakes", category: "Dehydrated Vegetables", description: "Dehydrated beetroot slices. Retains deep purple color and earthy sweetness." },
    { id: "fried-onion-flakes", name: "Fried Onion Flakes", category: "Fried & Toasted", description: "Golden fried crispy onion flakes. Ready-to-use garnish for Biryani and burgers." }
];

const fullProducts = newProducts.map(p => ({
    ...p,
    price: Math.floor(Math.random() * 500) + 100,
    image: `/images/products/${p.id}.png`,
    keywords: [p.name.toLowerCase(), "export quality", "organic", "natural"],
    popularity: Math.floor(Math.random() * 30) + 60,
    origin: "Maharashtra, India",
    moq: "5 MT",
    hsCode: "0712.90",
    exportStandards: "FSSAI, Export Grade, Non-GMO",
    packagingOptions: ["25 kg PP Bag", "Custom Branding"],
    variety: "Premium",
    moisture: "≤ 8%"
}));

const fs = require('fs');
fs.writeFileSync('new_products.json', JSON.stringify(fullProducts, null, 4));
