-- ==========================================
-- 1. Insert Initial Products
-- ==========================================

INSERT INTO products (name, category, origin, quality_standards, packaging, export_capacity, description, image_url, is_active) VALUES
('Basmati Rice', 'Food Grains', 'Punjab, Haryana, Madhya Pradesh', 'FSSAI Certified, ISO 22000, Non-GMO', '25 kg / 50 kg PP bags, Custom packaging available', '500+ MT per month', 'Premium long-grain Basmati rice known for its distinct aroma and fluffy texture. Sourced directly from elite farmer clusters in North India.', '/src/assets/products-hero.png', true),
('Wheat', 'Food Grains', 'Madhya Pradesh, Punjab, Maharashtra', 'FSSAI Certified, Phyto-sanitary tested', '50 kg PP bags / Bulk loose in containers', '1000+ MT per month', 'High-protein Indian wheat suitable for flour milling, baking, and pasta production. Consistently graded for maximum yield.', '/src/assets/products-hero.png', true),
('Maize', 'Food Grains', 'Karnataka, Andhra Pradesh, Maharashtra', 'Aflatoxin controlled, Non-GMO', '50 kg PP bags / Bulk containerized', '2000+ MT per month', 'Yellow maize with high starch content, ideal for human consumption, animal feed, and industrial starch extraction.', '/src/assets/products-hero.png', true),
('Millets', 'Food Grains', 'Rajasthan, Maharashtra, Karnataka', 'Gluten-free, FSSAI Certified', '25 kg / 50 kg PP bags', '200+ MT per month', 'Nutrient-dense ancient grains including Pearl Millet (Bajra), Finger Millet (Ragi), and Sorghum (Jowar).', '/src/assets/products-hero.png', true),
('Tur Dal (Pigeon Pea)', 'Pulses', 'Maharashtra, Karnataka, Madhya Pradesh', 'Sortex Cleaned, Polished/Unpolished', '25 kg / 50 kg PP bags', '300+ MT per month', 'Premium quality, sortex-cleaned Tur Dal with high protein content and quick cooking profile.', '/src/assets/products-hero.png', true),
('Chana (Chickpeas)', 'Pulses', 'Madhya Pradesh, Rajasthan, Maharashtra', 'Machine cleaned, Size sorted', '25 kg / 50 kg PP bags', '500+ MT per month', 'Desi and Kabuli varieties available. Uniform size and excellent hydration properties for canning and hummus processing.', '/src/assets/products-hero.png', true),
('Moong (Green Gram)', 'Pulses', 'Rajasthan, Maharashtra', 'Sortex Cleaned', '25 kg / 50 kg PP bags', '200+ MT per month', 'Whole and split green gram, rich in protein and highly digestible. Perfect for sprouting and processing.', '/src/assets/products-hero.png', true),
('Urad (Black Gram)', 'Pulses', 'Andhra Pradesh, Maharashtra', 'Sortex Cleaned, Polished', '25 kg / 50 kg PP bags', '150+ MT per month', 'Whole and split black gram, essential for South Asian cuisine and papad manufacturing.', '/src/assets/products-hero.png', true),
('Turmeric Finger / Powder', 'Spices', 'Maharashtra (Sangli, Nanded), Telangana', 'High Curcumin (2-5%), Lead-free', '25 kg / 50 kg Jute/PP bags', '200+ MT per month', 'Vibrant yellow turmeric sourced from the renowned turmeric belts of Maharashtra and Telangana. Available in whole fingers or meticulously ground powder with verified curcumin content.', '/spices/turmeric1.jpg', true),
('Red Chilli (Whole & Powder)', 'Spices', 'Andhra Pradesh (Guntur), Telangana', 'ASTA Color certified, SHU tested', '10 kg / 25 kg bags', '300+ MT per month', 'Famous Guntur chillies ranging from mild color-enhancing varieties (Teja) to highly pungent variants (Byadgi). Available with and without stems.', '/spices/chilly.jpg', true),
('Coriander Seeds', 'Spices', 'Rajasthan, Gujarat, Madhya Pradesh', 'Machine cleaned, Eagle Quality', '25 kg / 40 kg PP bags', '150+ MT per month', 'Aromatic coriander seeds with high volatile oil content. Sorted to remove extraneous matter and available as whole seeds or fine powder.', '/src/assets/products-hero.png', true),
('Cumin Seeds (Jeera)', 'Spices', 'Gujarat (Unjha), Rajasthan', 'Singapore & Europe Quality (99%, 99.5%)', '25 kg / 50 kg PP bags', '100+ MT per month', 'Intensely flavorful cumin seeds, machine cleaned to meet exacting international standards (Singapore/Europe quality specifications).', '/spices/cumin1.webp', true),
('Soybean', 'Oilseeds', 'Madhya Pradesh, Maharashtra', 'Non-GMO, Machine Cleaned', '50 kg PP bags / Bulk containerized', '1500+ MT per month', 'High-protein, non-GMO soybeans suitable for oil extraction, soy meal production, and direct food applications.', '/src/assets/products-hero.png', true),
('Groundnut (Peanut)', 'Oilseeds', 'Gujarat, Andhra Pradesh', 'Aflatoxin-controlled, Size graded', '25 kg / 50 kg Jute/PP bags', '500+ MT per month', 'Bold and Java varieties available. Carefully processed to maintain low moisture and strictly controlled for aflatoxin levels.', '/src/assets/products-hero.png', true),
('Mustard Seeds', 'Oilseeds', 'Rajasthan, Haryana, Madhya Pradesh', 'Machine Cleaned', '50 kg PP bags', '300+ MT per month', 'Small, potent black and yellow mustard seeds with high oil content. Ideal for oil pressing and spice blends.', '/src/assets/products-hero.png', true),
('Red Onion', 'Fresh Produce', 'Maharashtra (Nashik, Pune)', 'Size graded (40mm-60mm+), Cured', '10 kg / 20 kg / 25 kg Mesh bags', '1000+ MT per month', 'Pungent red onions sourced from Nashik, globally renowned for their extended shelf life and robust flavor. Properly cured prior to export.', '/src/assets/products-hero.png', true),
('Fresh Fruits', 'Fresh Produce', 'Maharashtra, various', 'Export quality, Pre-cooled', 'Corrugated boxes', 'As per seasonal availability', 'A seasonal portfolio including Pomegranates (Bhagwa), Grapes, and Mangoes (Alphonso), handled through certified packhouses and cold chains.', '/src/assets/products-hero.png', true),
('Fresh Vegetables', 'Fresh Produce', 'Maharashtra', 'Export quality', 'Corrugated boxes', 'As per requirement', 'Assorted fresh vegetables including Green Chillies, Okra, and Bitter Gourd. Harvested and exported rapidly via air freight or short sea transit.', '/src/assets/products-hero.png', true);
